### ISSUE TITLE
Add a function to fetch cards

### ISSUE THREAD

**Issue by SimonChris** [paylike/Paylike.NET#7]
This wrapper does not seem to include a function to fetch a card from a card id. You can only retrieve card data when saving the card from a transaction, not when the card has been saved without a transaction.

**Comment by tjconcept** [comment]
Hi Simon,

A pull request for such an addition would be very welcome!

**Comment by SimonChris** [comment]
Give me push permissions then, and I will make the PR :).

**Comment by tjconcept** [comment]
Hi again,

You should fork the repository and open a PR to your branch.

**Comment by SimonChris** [comment]
Done :)

**Comment by SimonChris** [comment]
Added by https://github.com/paylike/Paylike.NET/pull/8
